# Custom CNPG Resource for Scheduled Backups
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: vegbankdb-scheduled-backup
spec:
  cluster:
    name: vegbankdb-cnpg # Name of the CNPG Cluster - you can confirm this by executing `kubectl get cluster -n vegbank-dev`
  method: volumeSnapshot
  backupOwnerReference: self
  schedule: '0 0 21 * * *' # 9PM UTC Daily - Six-term cron schedule specification: https://cloudnative-pg.io/documentation/1.20/backup/
  immediate: true