## Example values overrides, for deploying Metacat's database on the NCEAS k8s cluster
## Typically, you would keep these overrides alongside your application's environment-specific
## values-overrides yaml file, so they are versioned together with your application.
##
## How to deploy a cluster with this example file:
##
## $ helm install <releasename> oci:////ghcr.io/dataoneorg/charts/cnpg --version <version> \
##                              -f ./examples/values-overrides-metacat-dev.yaml

cnpg:
  dbName: metacat

  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

  persistence:
    size: 10Gi

  postgresql:
    ## metacat override to allow password auth:
    pg_hba:
      # TYPE        DATABASE      USER          ADDRESS         METHOD
      - host        metacat       metacat       0.0.0.0/0       password
      - host        metacat       metacat       ::0/0           password
      - host        all           postgres      0.0.0.0/0       password
      - host        all           postgres      ::0/0           password
