## Example values overrides, for deploying Metacat's database on the NCEAS k8s cluster
## Typically, you would keep these overrides alongside your application's environment-specific
## values-overrides yaml file, so they are versioned together with your application.
##
## How to deploy a cluster with this example file:
##
## $ helm install <releasename> oci:////ghcr.io/dataoneorg/charts/cnpg --version <version> \
##                              -f ./examples/values-overrides-metacat-dev.yaml

dbName: metacat
#dbUser: defaults to dbName if blank

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi

init:
  method: "pg_basebackup"
  pg_basebackup:
    source: "source-db"
    ## target database name and owner to create after cloning from the source
    database: "metacat"
    owner: "metacat"  # Defaults to the value of the pg_basebackup.database key.
    ## Name of the secret containing the initial credentials for the owner of the user database. If
    ## empty a new secret will be created from scratch
    secret:
      name: ""
    ## Necessary if the source database was initialized with libc locale provider
    localeProvider: libc

  externalClusters:
    - name: source-db
      connectionParameters:
        host: metacatbrooke-postgresql
        user: metacat
        dbname: metacat
        sslmode: disable
      password:
        name: metacatbrooke-metacat-secrets
        key: POSTGRES_PASSWORD


persistence:
  size: 10Gi

postgresql:
  ## metacat override to allow password auth:
  pg_hba:
    # TYPE        DATABASE      USER          ADDRESS         METHOD
    - host        metacat       metacat       0.0.0.0/0       password
    - host        metacat       metacat       ::0/0           password
    - host        all           postgres      0.0.0.0/0       password
    - host        all           postgres      ::0/0           password
