## Example values overrides, for updating a pre-existing Metacat database on the NCEAS k8s cluster
## (without initializing it again), and enabling volumeSnapshot backups on a cron schedule.
##
## Typically, you would keep these overrides alongside your application's environment-specific
## values-overrides yaml file, so they are versioned together with your application.
##
## How to upgrade a cluster with this example file:
##
## $ helm upgrade <releasename> oci://ghcr.io/dataoneorg/charts/cnpg --version <version> \
##                              -f ./examples/values-overrides-metacat-dev-backups.yaml

dbName: metacat
#dbUser: defaults to dbName if blank

resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi

persistence:
  size: 20Gi

init:
  enabled: false

postgresql:
  parameters:
    max_wal_senders: 16

  ## metacat override to allow password auth:
  pg_hba:
    # TYPE        DATABASE      USER          ADDRESS         METHOD
    - host        metacat       metacat       0.0.0.0/0       password
    - host        metacat       metacat       ::0/0           password
    - host        all           postgres      0.0.0.0/0       password
    - host        all           postgres      ::0/0           password

backup:
  enabled: true
  ## @param backup.schedule six-term cron schedule for creating snapshots
  ## Uses the six-term cron schedule specification, which is different from standard cron, since
  ## it includes a seconds field as the first entry.
  ## see: https://cloudnative-pg.io/documentation/current/backup/#cron-schedule
  ##
  ##   Field name   | Mandatory? | Allowed values  | Allowed special characters
  ##   ----------   | ---------- | --------------  | --------------------------
  ##   Seconds      | Yes        | 0-59            | * / , -
  ##   Minutes      | Yes        | 0-59            | * / , -
  ##   Hours        | Yes        | 0-23            | * / , -
  ##   Day of month | Yes        | 1-31            | * / , - ?
  ##   Month        | Yes        | 1-12 or JAN-DEC | * / , -
  ##   Day of week  | Yes        | 0-6 or SUN-SAT  | * / , - ?
  ##
  schedule: "0 0 21 1 * *"    # 9PM UTC on the first of each month
