## Create a PostgreSQL cluster using the CloudNative-PG operator
## (https://github.com/cloudnative-pg/cloudnative-pg)
##
{{ $validMethods := tuple "initdb" "pg_basebackup" "recovery" "snapshot_recovery" }}
{{- $initMethod := .Values.init.method | default "initdb" }}
{{- if not (has $initMethod $validMethods) }}
{{ required ( printf ".Values.init.method must be one of %s" $validMethods ) "" | fail }}
{{- end }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-cnpg
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.imageOverrideSpec }}
  imageName: {{ .Values.imageOverrideSpec }}
  {{- end }}
  instances: {{ .Values.instances | default 3 }}
  {{- if .Values.init.enabled }}
  bootstrap:
    {{- if eq $initMethod "initdb" }}
    initdb:
      database: {{ .Values.dbName }}
      owner: {{ .Values.dbUser }}
      secret:
        name: {{ .Values.existingSecret }}
      encoding: UTF8
      localeProvider: icu
      icuLocale: en_US
      localeCType: en_US.UTF-8
      localeCollate: en_US.UTF-8
      {{- with .Values.init.import }}
      import:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if or (eq $initMethod "recovery") (eq $initMethod "snapshot_recovery") }}
    recovery:
      {{- if eq $initMethod "recovery" }}
      backup:
        name: {{ .Values.init.recoverFromBackup }}
      {{- else }}
      volumeSnapshots:
        storage:
          name: {{ .Values.init.recoverFromSnapshot }}
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io
      {{- end }}
      database: {{ .Values.dbName }}
      owner: {{ .Values.dbUser }}
      secret:
        name: {{ .Values.existingSecret }}
    {{- end }}
    {{- if eq $initMethod "pg_basebackup" }}
    {{- with .Values.init.pg_basebackup }}
    pg_basebackup:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.replica }}
  replica:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.init.externalClusters }}
  externalClusters:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  postgresql:
    parameters:
      {{- range $k, $v := .Values.postgresql.parameters }}
        {{ $k }}: {{ $v | toString | quote }}
      {{- end }}
    {{- with .Values.postgresql.pg_hba }}
    pg_hba:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    pg_ident:
    {{- with .Values.postgresql.pg_ident }}
      {{- toYaml . | nindent 6 }}
    {{- else }}
      - local    postgres    {{ .Values.dbUser | default .Values.dbName }}
    {{- end }}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storage:
    storageClass: {{ .Values.persistence.storageClass }}
    size: {{ .Values.persistence.size }}
  {{- with .Values.backup }}
  {{- if .enabled }}
  backup:
    {{- omit . "enabled" "schedule" | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
