# Create a custom CNPG Resource for Scheduled Backups
# Scheduled backups are enabled via 'values.yaml'
{{- if .Values.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Release.Name }}-scheduled-backup
spec:
  cluster:
    name: {{ .Release.Name }}-cnpg
  method: volumeSnapshot
  backupOwnerReference: self
  schedule: '0 0 21 * * *' # 9PM UTC Daily - Six-term cron schedule specification: https://cloudnative-pg.io/documentation/1.20/backup/
  immediate: true
{{- end }}